name: video_slimmer
description: "一个极致简洁、功能强大的移动端视频压缩工具。通过手机智能算法让每一用户都能轻松缩小视频体积，解决存储焦虑和分享困难的问题。"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  photo_manager: ^3.0.0
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.4.9
  go_router: ^14.2.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.7
  shared_preferences: ^2.3.2
  video_player: ^2.9.1
  path_provider: ^2.1.5
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  remixicon: ^1.4.1
  ffmpeg_kit_flutter_new: ^4.1.0
  uuid: ^4.5.1
  pool: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
